### ISSUE TITLE
Caddy crashes when Naiveproxy SUoT option enabled 

### ISSUE THREAD

**Issue by amd64v3** [SagerNet/sing#8]
Sorry I can't see the  issue template, so I directly describe about the problem I encountered.

What happend:

I have built Caddy with <a href="https://github.com/SagerNet/forwardproxy">SagerNet/forwardproxy</a> to use Naiveproxy with SUoT support, but it  crashes so many times.

When does it appear:

When I test uploading speed with Speedtest or uploading big files to Telegram. (PS: Maybe it will appear when extensive use of upload bandwidth, and it only appear when SUoT option enabled. )

After this,  I forked the  forwardproxy module and update Sing to the latest commit, but it still crashed, and both logs and errors were the same, here are the Caddy error log:

caddy[1310]: goroutine 52445 [running]:
caddy[1310]: github.com/sagernet/sing/common/buf.(*Buffer).ReadFullFrom(0x1e22540?, {0x1e22540?, 0xc0001206f8?}, 0x2af4a50?)
caddy[1310]:         github.com/sagernet/sing@v0.0.0-20220914045234-93cc53b60cee/common/buf/buffer.go:205 +0xaf
caddy[1310]: github.com/sagernet/sing/common/uot.(*ServerConn).loopInput(0xc001076390)
caddy[1310]:         github.com/sagernet/sing@v0.0.0-20220914045234-93cc53b60cee/common/uot/server.go:71 +0x37f
caddy[1310]: created by github.com/sagernet/sing/common/uot.NewServerConn
caddy[1310]:         github.com/sagernet/sing@v0.0.0-20220914045234-93cc53b60cee/common/uot/server.go:25 +0x305
systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: caddy.service: Failed with result 'exit-code'.
systemd[1]: caddy.service: Consumed 10.740s CPU time.

After this I  built Caddy with  <a href="https://github.com/SagerNet/UoT">SagerNet/UoT</a>,   it still crashed, here are the Caddy error log:

caddy[1255]: goroutine 31760 [running]:
caddy[1255]: github.com/sagernet/uot/common/buf.(*Buffer).ReadFullFrom(0x1e1c4e0?, {0x1e1c4e0?, 0xc0001bc658?}, 0x2aeb970?)
caddy[1255]:         github.com/sagernet/uot@v0.0.0-20220403125237-bf82029ad617/common/buf/buffer.go:161 +0x14d
caddy[1255]: github.com/sagernet/uot.(*ServerConn).loopInput(0xc000c361b0)
caddy[1255]:         github.com/sagernet/uot@v0.0.0-20220403125237-bf82029ad617/server.go:69 +0x247
caddy[1255]: created by github.com/sagernet/uot.NewServerConn
caddy[1255]:         github.com/sagernet/uot@v0.0.0-20220403125237-bf82029ad617/server.go:25 +0x305
systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: caddy.service: Failed with result 'exit-code'.
systemd[1]: caddy.service: Consumed 6.829s CPU time.

Environment: 

Server: Debian11, Caddy 2.5.2
Client: Lineage OS 18.1, SagerNet 0.8.1-rc02, naive-plugin-103.0.5060.53-1

**Comment by nekohasekai** [comment]
Please submit full crash log, and sing-box now supports naive server.

**Comment by amd64v3** [comment]
[caddy.log](https://github.com/SagerNet/sing/files/9567451/caddy.log)
Is it useful?

**Comment by nekohasekai** [comment]
I mean the full crash log.

**Comment by amd64v3** [comment]
I found it from journalctl, "slice bounds out of range",  maybe that's why it happened?
 
Sep 14 07:45:22 debian caddy[1255]: caddy.HomeDir=/root
Sep 14 07:45:22 debian caddy[1255]: caddy.AppDataDir=/root/.local/share/caddy
Sep 14 07:45:22 debian caddy[1255]: caddy.AppConfigDir=/root/.config/caddy
Sep 14 07:45:22 debian caddy[1255]: caddy.ConfigAutosavePath=/root/.config/caddy/autosave.json
Sep 14 07:45:22 debian caddy[1255]: caddy.Version=v2.5.2 h1:eCJdLyEyAGzuQTa5Mh3gETnYWDClo1LjtQm2q9RNZrs=
Sep 14 07:45:22 debian caddy[1255]: runtime.GOOS=linux
Sep 14 07:45:22 debian caddy[1255]: runtime.GOARCH=amd64
Sep 14 07:45:22 debian caddy[1255]: runtime.Compiler=gc
Sep 14 07:45:22 debian caddy[1255]: runtime.NumCPU=2
Sep 14 07:45:22 debian caddy[1255]: runtime.GOMAXPROCS=2
Sep 14 07:45:22 debian caddy[1255]: runtime.Version=go1.19.1
Sep 14 07:45:22 debian caddy[1255]: os.Getwd=/
Sep 14 07:45:22 debian caddy[1255]: LANG=en_US.UTF-8
Sep 14 07:45:22 debian caddy[1255]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Sep 14 07:45:22 debian caddy[1255]: NOTIFY_SOCKET=/run/systemd/notify
Sep 14 07:45:22 debian caddy[1255]: HOME=/root
Sep 14 07:45:22 debian caddy[1255]: LOGNAME=root
Sep 14 07:45:22 debian caddy[1255]: USER=root
Sep 14 07:45:22 debian caddy[1255]: SHELL=/bin/sh
Sep 14 07:45:22 debian caddy[1255]: INVOCATION_ID=9f66a401b6af42f4bf827d6784200133
Sep 14 07:45:22 debian caddy[1255]: JOURNAL_STREAM=8:18384
Sep 14 07:45:22 debian caddy[1255]: {"level":"info","ts":1663155922.2128453,"msg":"using provided configuration","config_file":"/usr/local/etc/caddy/caddy.json","config_adapter":""}
Sep 14 07:45:22 debian caddy[1255]: {"level":"info","ts":1663155922.2149112,"msg":"redirected default logger","from":"stderr","to":"/var/log/caddy/access.log"}
**Sep 14 07:48:41 debian caddy[1255]: panic: runtime error: slice bounds out of range [:49695] with capacity 20480**
Sep 14 07:48:41 debian caddy[1255]: goroutine 31760 [running]:
Sep 14 07:48:41 debian caddy[1255]: github.com/sagernet/uot/common/buf.(*Buffer).ReadFullFrom(0x1e1c4e0?, {0x1e1c4e0?, 0xc0001bc658?}, 0x2aeb970?)
Sep 14 07:48:41 debian caddy[1255]:         github.com/sagernet/uot@v0.0.0-20220403125237-bf82029ad617/common/buf/buffer.go:161 +0x14d
Sep 14 07:48:41 debian caddy[1255]: github.com/sagernet/uot.(*ServerConn).loopInput(0xc000c361b0)
Sep 14 07:48:41 debian caddy[1255]:         github.com/sagernet/uot@v0.0.0-20220403125237-bf82029ad617/server.go:69 +0x247
Sep 14 07:48:41 debian caddy[1255]: created by github.com/sagernet/uot.NewServerConn
Sep 14 07:48:41 debian caddy[1255]:         github.com/sagernet/uot@v0.0.0-20220403125237-bf82029ad617/server.go:25 +0x305

**Comment by nekohasekai** [comment]
Try 38f39bc0c69010bd9666e1690ddc1f292ddcfad2

**Comment by amd64v3** [comment]
Thanks, it has been fixed.
